// 错误码映射
export const ERROR_CODES = {
  // 成功
  SUCCESS: 'SUCCESS',

  // 系统错误
  SYSTEM_ERROR: 'FAIL_SYS_ERROR',
  TOKEN_EXPIRED: 'FAIL_SYS_TOKEN_EXOIRED',
  ILLEGAL_REQUEST: 'FAIL_SYS_ILLEGAL_REQUEST',
  SERVICE_NOT_EXIST: 'FAIL_SYS_SERVICE_NOT_EXIST',
  TIMEOUT: 'FAIL_SYS_TIMEOUT',

  // 业务错误
  USER_NOT_LOGIN: 'FAIL_BIZ_USER_NOT_LOGIN',
  ITEM_NOT_FOUND: 'FAIL_BIZ_ITEM_NOT_FOUND',
  PERMISSION_DENIED: 'FAIL_BIZ_PERMISSION_DENIED',
  PARAM_ERROR: 'FAIL_BIZ_PARAM_ERROR',

  // 限流错误
  RATE_LIMIT: 'FAIL_SYS_TRAFFIC_LIMIT',
  USER_LIMIT: 'FAIL_SYS_USER_LIMIT',

  // 网络错误（自定义）
  NETWORK_ERROR: 'NETWORK_ERROR',
  REQUEST_TIMEOUT: 'REQUEST_TIMEOUT',
  INVALID_RESPONSE: 'INVALID_RESPONSE',
} as const;

// 错误消息映射
export const ERROR_MESSAGES: Record<string, string> = {
  [ERROR_CODES.SUCCESS]: '成功',
  [ERROR_CODES.SYSTEM_ERROR]: '系统错误',
  [ERROR_CODES.TOKEN_EXPIRED]: '令牌已过期，请重新登录',
  [ERROR_CODES.ILLEGAL_REQUEST]: '非法请求',
  [ERROR_CODES.SERVICE_NOT_EXIST]: '服务不存在',
  [ERROR_CODES.TIMEOUT]: '请求超时',
  [ERROR_CODES.USER_NOT_LOGIN]: '用户未登录',
  [ERROR_CODES.ITEM_NOT_FOUND]: '商品不存在',
  [ERROR_CODES.PERMISSION_DENIED]: '权限不足',
  [ERROR_CODES.PARAM_ERROR]: '参数错误',
  [ERROR_CODES.RATE_LIMIT]: '请求过于频繁，请稍后再试',
  [ERROR_CODES.USER_LIMIT]: '用户请求次数超限',
  [ERROR_CODES.NETWORK_ERROR]: '网络错误',
  [ERROR_CODES.REQUEST_TIMEOUT]: '请求超时',
  [ERROR_CODES.INVALID_RESPONSE]: '响应格式错误',
};

// 需要重试的错误码
export const RETRY_ERROR_CODES = [
  ERROR_CODES.TIMEOUT,
  ERROR_CODES.NETWORK_ERROR,
  ERROR_CODES.REQUEST_TIMEOUT,
] as const;

// 需要刷新token的错误码
export const TOKEN_ERROR_CODES = [
  ERROR_CODES.TOKEN_EXPIRED,
  ERROR_CODES.USER_NOT_LOGIN,
] as const;
